### PR TITLE
Add IncludeFilePaths and AdditionalDefines properties for custom node 

### PR DESCRIPTION
**Pull request by adam-wolski**
Unreal custom node in which our HLSL code is placed has useful properties for defines and include paths.

This allows for more possibilities when creating hlsl material functions including usage of .ush files.

This pull request adds ability to set those properties for all functions in library as well as update function on changes to included files.

As just adding those properties was very easy most of the code changes are related to watching for changes in includes and supporting that properly.

### CODE REVIEW

**Comment by Phyronnaz** [comment]
Thanks for the contribution!

The change looks good. 

My idea with the library was to keep it as just a bridge between the HLSL file and the function assets.
Keeping all the data in the HLSL file should allow for much better diffs.

Storing the includes & the defines in there somewhat goes against that, so I might end up automatically parsing them from the HLSL code instead of having to enter them manually.

Do you have any thoughts on the matter? :)

**Comment by adam-wolski** [comment]
Thanks for looking into it so quickly!
Great job on the plugin BTW!

Parsing them would be better yes, I agree.
Though the more custom parsing is added the more edge cases will be found.

Next thing would be parsing global variables, then structs, then arrays and we end up with full hlsl parser 😄 

For a second I thought that maybe we could just use treesitter but I haven't found hlsl parser implemented.

I personally DO keep those includes in HLSL so I have them in diffs.
I do a little bit of trickery.
```hlsl
#ifndef HLSLFunctionLibrary
#include "Someheader.ush"
#endif
```
and I add `HLSLFunctionLibrary` define in function library asset.

This way my IDE knows what includes to use, they are included in source control, they are included in custom node and parser is fine.

But this of course is just a workaround(though not that bad).

**Comment by Phyronnaz** [comment]
Yeah having a full HLSL parser sure sounds fun 😄 

Out of curiosity, what IDE do you use for HLSL? I've tried VS, VS Code w/ HLSL Tools and Rider so far, but none of them are excellent.

One of my main pain point is no autocompletion for unreal uniform buffers - eg, `View` or `Primitive`. This makes writing something like
```hlsl
float2 ScreenPosition = (UV - View.ScreenPositionScaleBias.wz) / View.ScreenPositionScaleBias.xy;
```
much harder than it should be.

To mitigate that I'm looking into autogenerating an intellisense/hlsl file containing all the uniform buffer definitions. It's working great so far, but it sure sounds overkill :)

Another pain point is the defines. All the unreal shader files are full of defines (yay permutations), which among other things makes working with them in IDEs a pain because the IDE has no idea which defines are true/false.

I'm looking into exporting the defines list from a specific material (right before the shader compilation itself), but it's pretty tricky to do without any engine change.

Am I missing something, or is working with shaders just way behind the C++ workflows?

**Comment by adam-wolski** [comment]
I also tried all those 😄 
Now I'm usually using Rider. It at least knows what to ignore.

Having IDE work with unreal headers sure is pretty hard. 

To generate intelisense you would need to generate one depending on what vertex factory you are using on your mesh. 
That would be pretty tricky to get all that working.

Whole Unreal shader story is not ideal. 
With it being so reliant on material editor.

Adding "global" shaders is fine.

But trying to do anything that is supposed to work with materials, meshes, fit into normal pipeline is a big pain. Like reloading whole editor on every change pain.

**Comment by Phyronnaz** [comment]
Yeah, what I currently have ask you which permutation to use 🤔 
image

**Comment by adam-wolski** [comment]
Will you be releasing this? 😃 I'm sure even in this form it's quite useful.

**Comment by Phyronnaz** [comment]
I've pushed the change - you can access it by going to Window -> Permutation in the material editor. Clicking Generate HLSL will generate an Intellisense.hlsl. 

Including that at the top of your files will fixup a lot of things :)

On my side I've included it in Platform.ush, that way it's included literally everywhere & most defines work. However I wouldn't really recommend that in any kind of production use :smile:

image

**Comment by adam-wolski** [comment]
Thanks 😄

**Pull request merged**
